### PR TITLE
Second part of the fix for issue 17

### LINKED ISSUE #17: Wrongly parsed column values by Circus Train
During our GCP-AWS migration tasks we realized that there are separate column values which are not parsed appropriately by Circus Train. For example in one of the tables that we would like to migrate to AWS from GCP we have a similar value like this:

columnB = """{""""abcd"""":""""efgh1234""""","""""abcd"""":""""dcba1234""""}"""

Circus Train will split this value up along the comma. So in the output CSV we will get this separation:

columnA: ""
columnB: "{""abcd"":""efgh1234""
columnC: ""abcd"":""dcba1234""}"
columnD: ""

Landing table properties are:

ROW FORMAT SERDE
'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES (
'field.delim'=',',
'serialization.format'=',',
'skip.header.line.count'='1')
STORED AS INPUTFORMAT
'org.apache.hadoop.mapred.TextInputFormat'
OUTPUTFORMAT
'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'

I've tried to use OpenCSVSerde with ',' as separatorChar and '"' as quoteChar on the landing table on AWS, but it did not solve the issue entirely.
There are some cases when it would be great to have other than e.g. comma as a separator char in the output CSV.

### PR DESCRIPTION
**Pull request by AnanaMJ**
This PR is to cleanup the code after the previous PR (#18)
It also addresses one of the unresolved comments from that PR: https://github.com/HotelsDotCom/circus-train-bigquery/pull/18#discussion_r231838564

Fixes #17

### CODE REVIEW

File: src/main/java/com/hotels/bdp/circustrain/bigquery/partition/PartitionQueryFactory.java [hunk 1]
```diff
@@ -31,14 +31,14 @@
   public String newInstance(Table hiveTable, String partitionBy, String partitionFilter) {
     if (isNotBlank(partitionBy) && isNotBlank(partitionFilter)) {
       String query = String
-          .format("select distinct(%s) from %s.%s where %s group by %s order by %s", partitionBy, hiveTable.getDbName(),
-              hiveTable.getTableName(), partitionFilter, partitionBy, partitionBy);
+          .format("select distinct(%s) from %s.%s where %s order by %s", partitionBy, hiveTable.getDbName(),
```
Comment (massdosage) [inline src/main/java/com/hotels/bdp/circustrain/bigquery/partition/PartitionQueryFactory.java]: Why are the `group by` statements no longer needed?

File: src/main/java/com/hotels/bdp/circustrain/bigquery/extraction/container/DeleteTableAction.java [hunk 2]
```diff
@@ -31,8 +32,12 @@ public DeleteTableAction(Table table) {
 
   @Override
   public void run() {
-    table.delete();
-    log.debug("Deleted table '{}'", table.getTableId());
+    try {
+      table.delete();
+      log.debug("Deleted table '{}'", table.getTableId());
+    } catch (BigQueryException e) {
+      log.error("Could not delete BigQuery table '{}': {}", table.getTableId(), e.getMessage());
```
Comment (massdosage) [inline src/main/java/com/hotels/bdp/circustrain/bigquery/extraction/container/DeleteTableAction.java]: We should log `e` to get the full stack trace, not just `e.getMessage()`.

File: src/test/java/com/hotels/bdp/circustrain/bigquery/client/BigQueryMetastoreClientTest.java [hunk 3]
```diff
@@ -42,60 +40,45 @@
...
+  private final HiveTableCache cache = new HiveTableCache();
   private final Table hiveTable = new Table();
 
   @Before
   public void init() throws IOException {
     hiveTable.setTableName(tableName);
     hiveTable.setDbName(databaseName);
     bigQueryMetastoreClient = new BigQueryMetastoreClient(bigQueryMetastore, extractionService, cache, factory);
+
+    for (int i = 0; i < 10; ++i) {
```
Comment (massdosage) [inline src/test/java/com/hotels/bdp/circustrain/bigquery/client/BigQueryMetastoreClientTest.java]: minor but `i++` is the more common form so use that unless there's a really good reason not to.

File: src/main/java/com/hotels/bdp/circustrain/bigquery/partition/PartitionQueryFactory.java (hunk 1 above)
Comment (AnanaMJ) [reply src/main/java/com/hotels/bdp/circustrain/bigquery/partition/PartitionQueryFactory.java]: So before it was `select x from db.table where <condition> group by x order by x` and replacing it with `select distinct(x) from db.table where <condition> order by x` means the same thing, but is more specific to what the query is trying to get: a distinct list of all the values in the column.

I was looking into the difference between `distinct` and `group by` and found this: https://stackoverflow.com/questions/164319/is-there-any-difference-between-group-by-and-distinct.

File: src/main/java/com/hotels/bdp/circustrain/bigquery/extraction/container/DeleteTableAction.java (hunk 2 above)
Comment (AnanaMJ) [reply src/main/java/com/hotels/bdp/circustrain/bigquery/extraction/container/DeleteTableAction.java]: Does it mean it would turn into 
```
log.error("Could not delete BigQuery table '{}': ", table.getTableId(), e);
```
?

File: src/main/java/com/hotels/bdp/circustrain/bigquery/partition/PartitionQueryFactory.java (hunk 1 above)
Comment (massdosage) [reply src/main/java/com/hotels/bdp/circustrain/bigquery/partition/PartitionQueryFactory.java]: OK right, yes if you are selecting just X then it makes no sense to group by it as you will only ever have one group - X.

File: src/main/java/com/hotels/bdp/circustrain/bigquery/extraction/container/DeleteTableAction.java (hunk 2 above)
Comment (massdosage) [reply src/main/java/com/hotels/bdp/circustrain/bigquery/extraction/container/DeleteTableAction.java]: `log.error("Could not delete BigQuery table '{}'", table.getTableId(), e);`

No need for the ":" as the exception is already logged separately by the framework. You can try it out yourself in a simple main method to see the different outputs:

```
  public static void main(String[] args) {
    try {
      throw new RuntimeException("bla");
    } catch (Exception e) {
    log.error("Could not delete BigQuery table '{}'", "mytable", e);}
  }
```

Comment (AnanaMJ) [reply src/main/java/com/hotels/bdp/circustrain/bigquery/extraction/container/DeleteTableAction.java]: Ah okay, I realised that I had a tests that showed how the error is displayed. This is nicer, thank you.

File: src/main/java/com/hotels/bdp/circustrain/bigquery/partition/HivePartitionKeyAdder.java [hunk 4]
```diff
@@ -40,13 +39,13 @@ public Table add(String partitionKey, Schema filteredTableSchema) {
...
 
-    BigQueryToHiveTypeConverter typeConverter = new BigQueryToHiveTypeConverter();
     for (Field field : filteredTableSchema.getFields()) {
       String fieldName = field.getName().toLowerCase().trim();
       if (partitionKey.equals(fieldName)) {
         FieldSchema fieldSchema = new FieldSchema();
         fieldSchema.setName(fieldName);
-        fieldSchema.setType(typeConverter.convert(field.getType().toString()).toLowerCase());
+        // all partition types are string
+        fieldSchema.setType(FIELD_SCHEMA_TYPE);
```
Comment (massdosage) [inline src/main/java/com/hotels/bdp/circustrain/bigquery/partition/HivePartitionKeyAdder.java]: I guess this is also a change that should be mentioned in the changelog?

Comment (AnanaMJ) [reply src/main/java/com/hotels/bdp/circustrain/bigquery/partition/HivePartitionKeyAdder.java]: Done 👍

File: src/main/java/com/hotels/bdp/circustrain/bigquery/extraction/container/DeleteTableAction.java [hunk 5]
```diff
@@ -31,8 +32,12 @@ public DeleteTableAction(Table table) {
 
   @Override
   public void run() {
-    table.delete();
-    log.debug("Deleted table '{}'", table.getTableId());
+    try {
+      table.delete();
+      log.debug("Deleted table '{}'", table.getTableId());
+    } catch (BigQueryException e) {
```
Comment (massdosage) [inline src/main/java/com/hotels/bdp/circustrain/bigquery/extraction/container/DeleteTableAction.java]: Also needs to be mentioned in changelog - if an error occurs deleting an intermediate table during cleanup this will no longer fail the replication but now will just log an error and continue.

File: src/test/java/com/hotels/bdp/circustrain/bigquery/extraction/service/ExtractionServiceTest.java [hunk 6]
```diff
@@ -76,16 +98,66 @@ public void cleanup() {
...
+    actions.add(updateTableSchemaAction);
+    service.register(container);
+    service.extract();
+    verify(deleteTableAction).run();
+    verify(updateTableSchemaAction).run();
+    verify(updatePartitionSchemaAction).run();
+  }
+
+  @Test
+  public void runActionsWithTableDeletionError() {
```
[the remark this answers is not in the document]
Comment (AnanaMJ) [reply src/test/java/com/hotels/bdp/circustrain/bigquery/extraction/service/ExtractionServiceTest.java]: Why? If the `DeleteTableAction` has an internal failure, I need to test that it still runs, but if the other two classes that implement `PostExtractionAction` have an internal failure, then I need to check that other things won't run either.

I could remove them from here completely, but to keep that behaviour tested, I would move each test to the test class it belongs.

[the remark this answers is not in the document]
Comment (patduin) [reply src/test/java/com/hotels/bdp/circustrain/bigquery/extraction/service/ExtractionServiceTest.java]: that should be tested in the DeleteTableActionTest not here. The code doesn't know anything about DeleteTableAction neither does the test it should be decoupled.
